# Generated by Django 4.2.2 on 2024-09-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
            ],
        ),
    ]
