# Generated by Django 4.2.2 on 2024-09-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afridu_app', '0002_registration_position_registration_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attachemt',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
