# Generated by Django 4.2.2 on 2024-09-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afridu_app', '0003_registration_attachemt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='attachemt',
            new_name='attachment',
        ),
    ]
