# Generated by Django 4.2.2 on 2024-09-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afridu_app', '0005_alter_registration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='dob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
