# Generated by Django 4.2.2 on 2024-09-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afridu_app', '0006_registration_dob_registration_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
