# Generated by Django 4.2.2 on 2024-09-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afridu_app', '0007_alter_registration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
