# Generated by Django 4.2.2 on 2024-09-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afridu_app', '0009_alter_registration_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dob',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
