# Generated by Django 4.2.16 on 2024-09-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afridu_app', '0010_alter_registration_dob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('-submitted_at',)},
        ),
    ]
